development:
  app_name: "Sample_app"

links:
  rails_home: "http://www.railstutorial.org/"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
digits:
  digit_6: 6
  digit_50: 50
  digit_140: 140
pagy:
  page_10: 10
email:
  from_address: "noreply@example.com"
user_mailer:
  host: localhost:3000
  protocol: http

mailer:
  expire_hour: 2
  items: 10
sizes:
  size_80: 80
uploads:
    image_types:
      - image/jpeg
      - image/gif
      - image/png
